---
title: Jacksonville Pokemon Go
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@jacksonvillepokemongo.com
description: Domain available
url: http://jacksonvillepokemongo.com
google-verification: KCKo3GaDV2eE-OAAnsOb-UZbFZ_ZxjkztjpM3Vf6MVo
exclude:
- LICENSE
- README.md
- CNAME
- archive
markdown: kramdown
highlighter: rouge
