# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacksonville Pokemon Go
email: info@jacksonvillepokemongo.com
description: Domain available

url: http://jacksonvillepokemongo.com # the base hostname & protocol for your site

exclude:
    - LICENSE
    - README.md
    - CNAME
    - archive

# Build settings
markdown: kramdown
highlighter: rouge
